apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: server-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: local.ecosia.org
      http:
        paths:
          - path: /
            backend:
              serviceName: server
              servicePort: 5000