name: Minikube start and deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying minikube
        
    steps:
    
      # Build Steps
      - name: Checkout Code
        uses: actions/checkout@v2    
      - name: Start Minikube
        id: minikube
        uses: hiberbee/github-action-minikube@latest
        with:
          profile: github
          minikube-version: 1.20.0
          addons: default-storageclass,storage-provisioner,ingress
      - name: Try the cluster !
        run: sleep 10 && kubectl get pods -A
      - name: Run everything
        run: ./build.sh     
        
  
    
