name: Minikube start and deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying minikube
        
    steps:
    
      # Build Steps
      - name: Checkout Code
        uses: actions/checkout@v2    
      - name: Start minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.17.0'
          kubernetes version: 'v1.19.2'
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Run everything
        run: ./build.sh     
        
  
    